### ISSUE TITLE
Set up redirects for old URLs?

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/praxis#63]
DH Now highlighted the [http://praxis.scholarslab.org/tutorials/bash/](http://praxis.scholarslab.org/tutorials/bash/) resource [here](http://digitalhumanitiesnow.org/2013/10/resource-command-line-bootcamp-the-praxis-program/), but it's no longer at that address. Feel free to close this if we'd prefer to not worry about redirects for older things like this...

**Comment by walshbr** [comment]
Fixed in https://github.com/scholarslab/praxis/commit/3ae6aee0a0d40eea5b4c52c4301d1fadf67fec39
Weirdly I'm not certain we ever had a link at that address…I did restructure things, but I'm not sure we ever had /tutorials/ as a directory. It used be called the scratchpad. I'm sure how to go about redirecting beyond one to one solutions like the ones in that commit since we're hosting on gh-pages. I'll close for now as this particular issue is closed though.
